### ISSUE TITLE
HLO: Spellbook not fully imported

### ISSUE THREAD

**Issue by JamzTheMan** [zarmstrong/hlo-importer#13]
When importing my wizard, it didn't import all the spells he knows.

I forget exactly which but either it only imported the spells I currently have memorized and/or only my "free" spells section of the spellbook. I had several more in the same spellbook added/bought and those didn't seem to import.

*Still saved me a LOT of time! Woot! Keep up the good work :)

**Comment by zarmstrong** [comment]
Send me the export token so I can try to reproduce :)

**Comment by JamzTheMan** [comment]
I just updated #14 with token and screenshot. Can test both issues with same character :)

**Comment by zarmstrong** [comment]
If you could, import your PC fresh and give me a list of the spells that are missing? he has quite a few so its hard for me to determine without seeing the PC in HLO

Also, hope on discord and join this server to reach me directly -- we can do some more in depth troubleshooting https://discord.gg/JPqBfwAyxk

**Comment by zarmstrong** [comment]
nevermind, hold off on this. I think i see the issue

**Comment by zarmstrong** [comment]
I think this is fixed now -- if you're not the GM, have the GM update the module and try again

**Comment by JamzTheMan** [comment]
This one still doesn't seem to be correct.  It looks like it's only pulling in spells I currently have "Memorized". Interesting enough, it pulls it only if "Memorized" is > 0, and doesn't matter what slot, i.e. Fireball imports ok because I have it memorized as Bonus Evocation Spells and Longstrider imports ok because I have it memorized in a 2nd level slot.

![image](https://user-images.githubusercontent.com/8051654/129110369-8948b699-3611-4968-b878-5762e29013d0.png)

What is NOT importing are spells from the "Spellbooks and Spells Summary" section in HLO. This is where you denote which spells you learn for free at each level, as well as any you "purchase".  For instance, I have Animate Rope as a 1rst level, but not memorized, so it's not being imported.

FWIW I don't really care if it can't import/set what I have memorized, as long as all the spells are added to my spell book TO memorize :)

I'll hop on the discord if you need more help.

![image](https://user-images.githubusercontent.com/8051654/129110470-af1cf1ca-dea5-400c-a634-55888fd976ae.png)

**Comment by zarmstrong** [comment]
Ah yes, this is a known issue. If you take a look at the json export from Herolab Online, you'll notice that they don't include spells that are not memorized.  I have an open ticket with them about it. There's nothing I can do, unfortunately. I recommend having all spells prepped if you want them to be included in the export. Obviously this will show an error within HLO that you have too many spells prepped, but it's the only work-around for the time being.
